# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtWidgets

from Ui.ui_main import UiMainWindow
from Ui.xss_ui_method import xss_get_input

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    main_window = UiMainWindow()
    main_window.show()

    main_window.xss_start_button.clicked.connect(lambda: xss_get_input(main_window))
    sys.exit(app.exec_())
